# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyeaux', '0002_auto_20161004_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSSlimsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_datetime', models.DateTimeField(verbose_name='collection datetime')),
                ('test_name', models.CharField(max_length=20, verbose_name='test name')),
                ('min_range', models.FloatField(blank=True, null=True, verbose_name='min range')),
                ('max_range', models.FloatField(blank=True, null=True, verbose_name='max range')),
                ('units', models.CharField(blank=True, max_length=10, verbose_name='units')),
                ('value_string', models.CharField(blank=True, max_length=10, verbose_name='value (string)')),
                ('value_number', models.FloatField(blank=True, null=True, verbose_name='value (float)')),
            ],
        ),
        migrations.CreateModel(
            name='PSSmicroResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_datetime', models.DateTimeField(verbose_name='collection datetime')),
                ('accession_number', models.CharField(blank=True, max_length=10, verbose_name='accession number')),
                ('testcode', models.CharField(max_length=5, verbose_name='test code')),
                ('batch_test_code', models.CharField(max_length=5, verbose_name='test code')),
                ('result_trans', models.TextField(blank=True, verbose_name='result translated')),
                ('result_modifiers', models.TextField(blank=True, verbose_name='result modifiers')),
                ('res_composed_text', models.TextField(blank=True, verbose_name='result text')),
                ('result_method', models.CharField(blank=True, max_length=4, verbose_name='Result Method')),
            ],
        ),
        migrations.CreateModel(
            name='PSSPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhsnumber', models.CharField(help_text='NHS Number', max_length=10, verbose_name='nhs number')),
                ('mrn', models.CharField(blank=True, max_length=8, verbose_name='mrn')),
                ('sex', models.CharField(blank=True, help_text='Gender', max_length=10, verbose_name='sex')),
                ('forename', models.CharField(blank=True, help_text='Forename', max_length=50, verbose_name='forename')),
                ('surname', models.CharField(blank=True, help_text='Surname', max_length=50, verbose_name='Surname')),
                ('birthdate', models.DateField(blank=True, help_text='date of birth', null=True, verbose_name='dob')),
                ('deathdate', models.DateField(blank=True, help_text='date of death', null=True, verbose_name='dod')),
                ('ethnic_group', models.CharField(blank=True, help_text='Ethnic Group', max_length=50, verbose_name='ethnic group')),
            ],
        ),
        migrations.AddField(
            model_name='pssmicroresult',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyeaux.PSSPerson'),
        ),
        migrations.AddField(
            model_name='psslimsresult',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyeaux.PSSPerson'),
        ),
    ]
