# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeaux', '0003_auto_20161020_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pssperson',
            name='nhsnumber',
            field=models.CharField(db_index=True, help_text='NHS Number', max_length=10, verbose_name='nhs number'),
        ),
    ]
